# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        ACCESS_TOKEN:${{ACCESS_TOKEN}}
        APP_VERSION:${{APP_VERSION}}
        CRON_FORMAT:${{CRON_FORMAT}}
        DEVICE_UUID:${{DEVICE_UUID}}
        LINE_NOTIFY_TOKEN:${{LINE_NOTIFY_TOKEN}}
        MC_HOST:${{MC_HOST}}
        MODEL_ID:${{MODEL_ID}}
        OS_VERSION:${{OS_VERSION}}
        PLATFORM:${{PLATFORM}}
        USER_ACCOUNT:${{USER_ACCOUNT}}
        USER_PASSWORD:${{USER_PASSWORD}}
